[vm_attaquant]
attaquant ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=/home/avernay/.ssh/sae52_attaquant_key

[vm_fw]
fw ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file=/home/avernay/.ssh/sae52_fw_key

[vm_cible_dmz]
cible_dmz ansible_host=192.168.56.20 ansible_user=vagrant ansible_ssh_private_key_file=/home/avernay/.ssh/sae52_cible_dmz_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
