Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # -------- VM ATTAQUANT --------
  config.vm.define "attaquant" do |a|
    a.vm.hostname = "attaquant"
    a.vm.network "private_network", ip: "192.168.56.10" # mgmt
    a.vm.network "private_network", virtualbox__intnet: "LAN", ip: "10.10.10.10"
    a.vm.provider "virtualbox" do |vb|
      vb.name = "sae52-attaquant"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # -------- VM FIREWALL --------
  config.vm.define "fw" do |f|
    f.vm.hostname = "fw"
    f.vm.network "private_network", ip: "192.168.56.12" # mgmt
    f.vm.network "private_network", virtualbox__intnet: "LAN", ip: "10.10.10.1"
    f.vm.network "private_network", virtualbox__intnet: "DMZ", ip: "10.10.20.1"
    f.vm.provider "virtualbox" do |vb|
      vb.name = "sae52-fw"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # -------- VM CIBLE DMZ --------
  config.vm.define "cible_dmz" do |c|
    c.vm.hostname = "cible-dmz"
    c.vm.network "private_network", ip: "192.168.56.20" # mgmt
    c.vm.network "private_network", virtualbox__intnet: "DMZ", ip: "10.10.20.20"
    c.vm.provider "virtualbox" do |vb|
      vb.name = "sae52-cible-dmz"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
