Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # ========= VM ATTAQUANTE / CONTROLEUR =========
  config.vm.define "attaquant" do |a|
    a.vm.hostname = "attaquant"
    a.vm.network "private_network", ip: "192.168.56.10"   # réseau management
    a.vm.network "private_network", virtualbox__intnet: "LAN", ip: "10.10.10.10"

    a.vm.provider "virtualbox" do |vb|
      vb.name = "sae52-attaquant"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # ========= VM CIBLE =========
  config.vm.define "cible" do |c|
    c.vm.hostname = "cible"
    c.vm.network "private_network", ip: "192.168.56.11"   # réseau management
    c.vm.network "private_network", virtualbox__intnet: "LAN", ip: "10.10.10.11"

    c.vm.provider "virtualbox" do |vb|
      vb.name = "sae52-cible"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
