FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
      python3 python3-pip \
      docker.io docker-compose-plugin && \
    pip3 install flask flask-cors && \
    apt-get clean

WORKDIR /scripts
CMD ["python3", "/scripts/control_api.py"]