FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
      python3 python3-pip \
      docker.io docker-compose && \
    pip3 install flask flask-cors && \
    apt-get clean

WORKDIR /project
CMD ["python3", "/project/scripts/control_api.py"]
