[targets]
target-web ansible_host=target-web ansible_connection=docker
target-db ansible_host=target-db ansible_connection=docker
target-api ansible_host=target-api ansible_connection=docker

[targets:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
