---
- name: Installer outils d'audit sur la VM attaquante
  hosts: vm_attaquant
  become: true
  tasks:
    - name: Paquets d'audit
      ansible.builtin.apt:
        name:
          - nmap
          - python3
          - python3-pip
          - curl
          - iproute2
          - iputils-ping
        state: present
        update_cache: yes

    - name: Créer arborescence audit
      ansible.builtin.file:
        path: /opt/audit/reports
        state: directory
        mode: "0755"
