---
- name: SAÉ 5.02 - Démo complète (réseau + service DMZ + audit)
  hosts: all
  gather_facts: false
  tasks: []

- import_playbook: 10_install_docker.yml
- import_playbook: 15_config_fw.yml
- import_playbook: 16_routes.yml
- import_playbook: 20_deploy_cible_dmz.yml
- import_playbook: 25_setup_audit_tools.yml
- import_playbook: 30_scan_nmap.yml
- import_playbook: 40_consolidate_reports.yml

